# Generated by Django 2.2 on 2022-10-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221021_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='v_obrabotke',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Coupon'),
        ),
    ]
