# Generated by Django 2.2 on 2023-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230301_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='acrtiul',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
