# Generated by Django 2.2 on 2023-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_item_acrtiul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='acrtiul',
            field=models.TextField(default='NONE', max_length=100),
        ),
    ]
