# Generated by Django 2.2 on 2023-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230308_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
